
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.63
distribution_type: module
version: 0.12
name: Devel-Pler
author: Adam Kennedy <adamk@cpan.org>
license: perl
build_requires: 
  Test::More: 0.47
  Test::Script: 0.01
requires: 
  File::Find::Rule: 0.20
  File::Spec: 0.80
  Exporter: 0
abstract: 
